/*
	Stephen Rice
	ProjectEuler.net
	September 23, 2013
	
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class P2
{
	long sum;
	long firstFib;
	long secFib;
	long newFib;
	
	//Set-up initial sum and fib numbers. Add 2 to the sum
	public P2()
	{
		sum = 0;
		firstFib = 1;
		secFib = 2;
		
		sum += secFib;
	}

	public long solve()
	{
		//Create each fib number and check if it is even. If so, add to sum
		while(newFib < 4000000)
		{
			newFib = firstFib + secFib;
			if(newFib % 2 == 0)
			{
				sum += newFib;
			}
			
			firstFib = secFib;
			secFib = newFib;
		}
		
		return sum;
	
	}
	
	
	public static void main(String[] args)
	{
		//Time and run the program
		long startTime = System.currentTimeMillis();
		P2 solver = new P2();
		double solution = solver.solve();
		long endTime = System.currentTimeMillis();
		
		//Print out the solution and time
		System.out.printf("Sum is %.0f",  solution);
		System.out.println("Took " + (endTime - startTime) + " milliseconds");
	}
	
}